@startuml tetris-container
title Diagrama de Contenedores del Sistema Tetris

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(jugador, "Jugador", "Usuario que interactúa con el videojuego")

System_Boundary(sistema_tetris_boundary, "Sistema de juego Tetris") {
    Container(ui, "Interfaz de Usuario", , "Muestra el tablero, tetrominos, puntuación, estado del juego y recibe las acciones del jugador")
    Container(motor_juego, "Motor de Lógica", ,"Gestiona el inicio, actualización, pausa, fin del juego y coordinación de reglas")

    Rel(jugador, ui, "Envia comandos de teclado para iniciar, mover, rotar, bajar y detener la partida")

    Rel(ui, motor_juego, "Envía acciones del jugador")
    Rel(motor_juego, ui, "Actualiza el estado del juego, tablero, tetrominos y puntuación")

}

@enduml